CREATE TABLE churches (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
slug VARCHAR(255) NOT NULL UNIQUE,
plan VARCHAR(50) DEFAULT 'FREE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);